[package]
name = "rustpyfibonacci"
version = "0.1.0"
edition = "2024"

[lib]
name = "fibonacci"
crate-type = ["cdylib"]
path = "src/rustpy/rustcode/src/lib.rs"

[dependencies]
rand = "0.9.0"


[dependencies.pyo3]
version = "0.24.0"
features = ["abi3-py38"]